### PR TITLE
Tweak laconicd config to allow setting endpoint port and to make the fixturenet restartable.

### PR DESCRIPTION
**Pull request by telackey**
Needed to let the endpoint sit behind an SSL proxy.

### CODE REVIEW

**Review by dboreham — COMMENTED** [review]
Are the create-fixturenet.sh changes related to pulling in a newer version of init.sh from laconicd?

**Comment by telackey** [comment]
No, but the actual changes are hard to see because of the indent:

```
diff --git a/stack_orchestrator/data/config/fixturenet-laconicd/create-fixturenet.sh b/stack_orchestrator/data/config/fixturenet-laconicd/create-fixturenet.sh
index 9c30bff..3b850f3 100644
--- a/stack_orchestrator/data/config/fixturenet-laconicd/create-fixturenet.sh
+++ b/stack_orchestrator/data/config/fixturenet-laconicd/create-fixturenet.sh
@@ -17,10 +17,9 @@ TRACE="--trace"
 # validate dependencies are installed
 command -v jq > /dev/null 2>&1 || { echo >&2 "jq not installed. More info: https://stedolan.github.io/jq/download/"; exit 1; }

+if [ ! -d "/root/.laconicd/data/blockstore.db" ]; then
   # remove existing daemon and client
-rm -rf ~/.laconic*
-
-make install
+  rm -rf ~/.laconicd/*

   laconicd config keyring-backend $KEYRING
   laconicd config chain-id $CHAINID
@@ -113,6 +112,9 @@ laconicd validate-genesis
   if [[ $1 == "pending" ]]; then
     echo "pending mode is on, please wait for the first block committed."
   fi
+else
+  echo "Using existing blockchain database."
+fi

 # Start the node (remove the --pruning=nothing flag if historical queries are not needed)
 laconicd start --pruning=nothing --evm.tracer=json $TRACE --log_level $LOGLEVEL --minimum-gas-prices=0.0001aphoton --json-rpc.api eth,txpool,personal,net,debug,web3,miner --api.enable --gql-server --gql-playground
```

**Comment by dboreham** [comment]
> No, but the actual changes are hard to see because of the indent.

Can you see if you can put the changes into the file in the laconicd repo, or come up with a refactoring that would make any changes here minimal and easy to see by diffing? The general idea is that this file shouldn't be maintained both here and in the laconicd repo. It's a bit of a hack that it's here in the first place.

**Comment by telackey** [comment]
Done: https://git.vdb.to/cerc-io/laconicd/pulls/117

**Review by dboreham — APPROVED** [review]

**Pull request merged**
